### DISCUSSION TITLE
pull access denied for frepple-community

### DISCUSSION THREAD

**Discussion by stcharles30** [frePPLe/frepple#634] [Q&A] [answered]
When i try bring my containers up using "docker compose up" - i get this error Error response from daemon: pull access denied for frepple-community, repository does not exist or may require 'docker login': denied: requested access to the resource is denied

Not sure if there is such a login required or if theres a different image to pull?

**Comment by jdetaeye** [comment]
Sorry for the late reply.
I believe github requires a login for these pulls.  It's (unfortunately) not an anynymous download.  

I couldn't find this explicitly in the github docs. So, if anybody else figured out to do this without github login, we're all interested to hear...

**Comment by sbadux** [comment, marked as answer]
I'm still having this issue also after logging in.
Docker compose login returned "Login Succeeded" and I've enabled the personal token to almost all the "scopes" from the github settings, but it doesn't work. Any idea?

`ERROR: pull access denied for frepple-community, repository does not exist or may require 'docker login': denied: requested access to the resource is denied`


EDIT: Since the command "docker pull ghcr.io/frepple/frepple-community:latest" worked fine I tried to change the first part of the docker-compose file from 


```
services:
  frepple:
    image: "frepple-community:latest"
    container_name: frepple-community-webserver
```


to 
```
services:
  frepple:
    image: "ghcr.io/frepple/frepple-community:latest"
    container_name: frepple-community-webserver
```

and the command worked without errors.
I'm not sure it is a good solution (or maybe it's not a solution at all) as I'm not expert. I wanted to report this, just in case
